# Generated by Django 5.2.11 on 2026-07-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reason',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(default='New', max_length=80),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='book_size',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='book_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='company',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='consent_to_contact',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='page_count',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('any', 'Any')], default='email', max_length=40),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='referral_source',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='timeline',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transportwaitlist',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='transportwaitlist',
            name='phone',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='transportwaitlist',
            name='status',
            field=models.CharField(default='New', max_length=80),
        ),
        migrations.AddField(
            model_name='transportwaitlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
