# Generated by Django 5.2.11 on 2026-07-09 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('copy', models.TextField(blank=True)),
                ('button_label', models.CharField(max_length=120)),
                ('button_url', models.CharField(max_length=240)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('style', models.CharField(blank=True, max_length=80)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF'), ('document', 'Document'), ('folder', 'Folder'), ('external', 'External URL')], default='image', max_length=40)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('external_url', models.URLField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=220)),
                ('usage', models.CharField(blank=True, max_length=180)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['asset_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RequestFormOptionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('options', models.JSONField(blank=True, default=list)),
                ('helper_text', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('value', models.TextField(blank=True)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('group', models.CharField(default='general', max_length=80)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['group', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=240)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120)),
                ('href', models.CharField(max_length=240)),
                ('area', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('mobile', 'Mobile'), ('admin', 'Admin')], default='header', max_length=40)),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('opens_new_tab', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sitecontent.navigationitem')),
            ],
            options={
                'ordering': ['area', 'display_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('portfolio', 'Portfolio'), ('shop', 'Shop'), ('courses', 'Courses'), ('reviews', 'Reviews'), ('contact', 'Contact'), ('request-project', 'Request Project'), ('transport', 'Transport')], max_length=80)),
                ('section_key', models.SlugField(max_length=120)),
                ('eyebrow', models.CharField(blank=True, max_length=160)),
                ('title', models.CharField(blank=True, max_length=220)),
                ('subtitle', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitecontent.mediaasset')),
            ],
            options={
                'ordering': ['page', 'display_order', 'section_key'],
                'unique_together': {('page', 'section_key')},
            },
        ),
    ]
