# Generated by Django 5.2.16 on 2026-07-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='display_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='display_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bank_transfer_ng', 'Nigerian Bank Transfer'), ('international_request', 'International Payment Request'), ('online_card', 'Online Card Payment')], default='international_request', max_length=40),
        ),
    ]
