# Generated by Django 5.2.16 on 2026-08-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_order_display_currency_order_display_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='order_receipts/'),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
