from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("summary", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="catalog/")),
                ("is_published", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("excerpt", models.TextField(blank=True)),
                ("author", models.CharField(default="Danajet", max_length=140)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("content", models.TextField(blank=True)),
                ("tags", models.CharField(blank=True, max_length=220)),
            ],
            options={"ordering": ["display_order", "title"]},
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("summary", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="catalog/")),
                ("is_published", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("code", models.CharField(blank=True, max_length=20)),
                ("name", models.CharField(max_length=140)),
                ("href", models.CharField(blank=True, max_length=220)),
            ],
            options={"ordering": ["display_order", "name"]},
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("summary", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="catalog/")),
                ("is_published", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("subtitle", models.CharField(blank=True, max_length=220)),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("status", models.CharField(default="Coming Soon", max_length=80)),
                ("video_url", models.URLField(blank=True)),
                ("duration", models.CharField(blank=True, max_length=80)),
                ("level", models.CharField(blank=True, max_length=80)),
                ("featured", models.BooleanField(default=False)),
            ],
            options={"ordering": ["display_order", "title"]},
        ),
        migrations.CreateModel(
            name="PortfolioProject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("summary", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="catalog/")),
                ("is_published", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("client", models.CharField(blank=True, max_length=180)),
                ("project_url", models.URLField(blank=True)),
                ("featured", models.BooleanField(default=False)),
                ("service_type", models.CharField(blank=True, max_length=140)),
            ],
            options={"ordering": ["display_order", "title"]},
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("summary", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="catalog/")),
                ("is_published", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("subtitle", models.CharField(blank=True, max_length=220)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("author", models.CharField(default="Danajet", max_length=140)),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("sale_price", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("amazon_url", models.URLField(blank=True)),
                ("rating", models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("age_range", models.CharField(blank=True, max_length=80)),
                ("format", models.CharField(blank=True, max_length=120)),
                ("featured", models.BooleanField(default=False)),
            ],
            options={"ordering": ["display_order", "title"]},
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("summary", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="catalog/")),
                ("is_published", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("reviewer_name", models.CharField(max_length=140)),
                ("reviewer_role", models.CharField(blank=True, max_length=180)),
                ("quote", models.TextField()),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("project", models.CharField(blank=True, max_length=180)),
                ("service", models.CharField(blank=True, max_length=120)),
                ("cta_label", models.CharField(blank=True, max_length=120)),
                ("cta_url", models.URLField(blank=True)),
            ],
            options={"ordering": ["display_order", "title"]},
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("summary", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="catalog/")),
                ("is_published", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("icon", models.CharField(blank=True, max_length=80)),
                ("starting_price", models.CharField(blank=True, max_length=80)),
            ],
            options={"ordering": ["display_order", "title"]},
        ),
    ]
