# Generated by Django 5.2.11 on 2026-07-09 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('category_type', models.CharField(choices=[('product', 'Product'), ('course', 'Course'), ('portfolio', 'Portfolio'), ('blog', 'Blog'), ('service', 'Service')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['category_type', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='brand',
            name='icon',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='brand',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='brand',
            name='status',
            field=models.CharField(default='Visible', max_length=80),
        ),
        migrations.AddField(
            model_name='course',
            name='access_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='embed_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='course',
            name='outcomes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='resources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='deliverables',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='review',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='service',
            name='availability',
            field=models.CharField(default='Available', max_length=80),
        ),
        migrations.AddField(
            model_name='service',
            name='deliverables',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='service',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='service',
            name='price_range',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='service',
            name='process_steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='service',
            name='request_url',
            field=models.CharField(default='/request-project', max_length=220),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='course',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_projects', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='service',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='catalog.category'),
        ),
    ]
